services:
  backend:
    build:
      context: ./StockProjectBackend
      dockerfile: Dockerfile
    command:
      - sh
      - -c
      - >
        python /app/firebase/fetch_firebase_secret.py
        && python manage.py collectstatic --noinput
        && python manage.py migrate --noinput
        && gunicorn StockAPI.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    # command:
    #   [
    #     "sh",
    #     "-c",
    #     "python /app/firebase/fetch_firebase_secret.py && python manage.py migrate --noinput && gunicorn StockAPI.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120",
    #   ]
    ports:
      - "80:8000"
    restart: unless-stopped
    environment:
      # All these will be injected from EB Environment Properties
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      EXTERNAL_API_KEY: ${EXTERNAL_API_KEY}
      AWS_REGION: ${AWS_REGION}
      FIREBASE_SECRET_NAME: ${FIREBASE_SECRET_NAME}
      FIREBASE_CREDENTIALS: ${FIREBASE_CREDENTIALS}
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      AWS_EB_HOST: ${AWS_EB_HOST}
      VERCEL_HOST: ${VERCEL_HOST}
      AWS_EB_HTTPS_DOM_ONE: ${AWS_EB_HTTPS_DOM_ONE}
      AWS_EB_HTTPS_DOM_TWO: ${AWS_EB_HTTPS_DOM_TWO}

  cronjob:
    build:
      context: ./StockProjectBackend
      dockerfile: Dockerfile.cron
    command:
      [
        "sh",
        "-c",
        "python /app/firebase/fetch_firebase_secret.py && /wait-for-backend.sh",
      ]
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      # Same envs so cronjob can hit backend + use Firebase
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      EXTERNAL_API_KEY: ${EXTERNAL_API_KEY}
      AWS_REGION: ${AWS_REGION}
      FIREBASE_SECRET_NAME: ${FIREBASE_SECRET_NAME}
      FIREBASE_CREDENTIALS: ${FIREBASE_CREDENTIALS}
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      AWS_EB_HOST: ${AWS_EB_HOST}
      VERCEL_HOST: ${VERCEL_HOST}
      AWS_EB_HTTPS_DOM_ONE: ${AWS_EB_HTTPS_DOM_ONE}
      AWS_EB_HTTPS_DOM_TWO: ${AWS_EB_HTTPS_DOM_TWO}
