services:
  backend:
    build:
      context: ./StockProjectBackend
      dockerfile: Dockerfile
    container_name: django-backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./StockProjectBackend:/app
      - ./StockProjectBackend/firebase/firebase-adminsdk.json:/app/firebase/firebase-adminsdk.json
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  cronjob:
    build:
      context: ./StockProjectBackend
      dockerfile: Dockerfile.cron
    container_name: cronjob
    volumes:
      - ./StockProjectBackend:/app
      - ./StockProjectBackend/firebase/firebase-adminsdk.json:/app/firebase/firebase-adminsdk.json
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
