# Generated by Django 5.2.2 on 2025-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('changes_percentage', models.FloatField()),
                ('change', models.FloatField()),
                ('day_low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('day_high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('year_high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('year_low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_cap', models.BigIntegerField()),
                ('price_avg_50', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price_avg_200', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('avg_volume', models.BigIntegerField()),
                ('exchange', models.CharField(max_length=50)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('previous_close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('eps', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pe', models.DecimalField(decimal_places=4, max_digits=20)),
                ('earnings_announcement', models.DateTimeField()),
                ('shares_outstanding', models.BigIntegerField()),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
    ]
