# Generated by Django 5.2.2 on 2025-06-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockAPICRUD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='avg_volume',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='earnings_announcement',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='pe',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shares_outstanding',
        ),
    ]
