# Generated by Django 5.2.2 on 2025-06-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockAPICRUD', '0002_remove_stock_avg_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='day_high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='day_low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='previous_close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_avg_200',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_avg_50',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='year_high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='year_low',
            field=models.FloatField(),
        ),
    ]
