# Generated by Django 5.2.2 on 2025-07-11 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockAPICRUD', '0003_alter_stock_day_high_alter_stock_day_low_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='stock',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='StockAPICRUD.listofstocks'),
        ),
    ]
