# Generated by Django 5.2.2 on 2025-07-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockAPICRUD', '0004_listofstocks_remove_stock_name_alter_stock_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='list',
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.TextField(default='UNKNOWN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.TextField(unique=True),
        ),
        migrations.DeleteModel(
            name='ListOfStocks',
        ),
    ]
