# Generated by Django 5.2.2 on 2025-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockAPICRUD', '0005_remove_stock_list_stock_name_alter_stock_symbol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.TextField(),
        ),
    ]
